In [106]:
# !pip install selenium
# !pip install openpyxl
import pandas as pd
import numpy as np
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
import time

In [ ]:
driver = webdriver.Chrome()

driver.maximize_window()

# explicit wait

wait = WebDriverWait(driver, 25)

# function to check if webpage is fully loaded 

def wait_for_page_to_load(driver, wait):
    # web for the webpage to load 
    # page_title=driver.title
    try: 
        # wait.until(
        #     lambda d: d.execute_script("return document.readyState") != "complete"
        #     )

        wait.until(
            lambda d: d.execute_script("return document.readyState") == "complete"
            )
    except:
        page_title = driver.title
        print(f"The page \"{page_title}\" did not get fully loaded within the given duration.\n")
    else:
        page_title = driver.title
        print(f"The page is \"{page_title}\" fully loaded.\n")


url = "https://finance.yahoo.com/"
driver.get(url)

wait_for_page_to_load(driver,wait)

# hovering on Markets menu
actions = ActionChains(driver)
markets_menu = wait.until(
    ec.presence_of_element_located((By.XPATH, "/html/body/div[1]/header/div/nav/ol/li[3]/a/div"))
)
actions.move_to_element(markets_menu).perform()

# hovering on stocks 
# actions = ActionChains(driver)
stocks_menu = wait.until(
    ec.presence_of_element_located((By.XPATH, "/html/body/div[1]/header/div/nav/ol/li[3]/ol/li[1]/a/span"))
)
actions.move_to_element(stocks_menu).perform()

# click on trending 
trending = wait.until(
    ec.element_to_be_clickable((By.XPATH, "/html/body/div[1]/header/div/nav/ol/li[3]/ol/li[1]/ol/li[4]/a/span"))
)
trending.click()

# temporary add and it is right
time.sleep(5)

wait_for_page_to_load(driver,wait)


# click on most active
most_active = wait.until(
    ec.element_to_be_clickable((By.XPATH, "/html[1]/body[1]/div[1]/div[4]/main[1]/section[1]/section[1]/section[1]/section[1]/section[1]/div[1]/div[1]/div[1]/a[1]"))
)
most_active.click()

# temporary add and it is right
time.sleep(5)

wait_for_page_to_load(driver,wait)




# scraping the data 
data=[]
while True:
    # scraping 
    wait.until(
        ec.presence_of_all_elements_located((By.TAG_NAME, "table"))
    )
    rows = driver.find_elements(By.CSS_SELECTOR, "table tbody tr")
    time.sleep(5)
    # print(len(rows))
    
    for row in rows:
        values = row.find_elements(By.TAG_NAME, "td")
        # time.sleep(5)
        print([val.text for val in values])
        stock = {
            "name": values[1].text,
            "symbol": values[0].text,
            "price": values[3].text,
            "change": values[4].text,
            "volume": values[6].text,
            "market_cap": values[8].text,
            "pe_ratio": values[9].text
        }
        
        data.append(stock)

    
    # click next 
    try:
        next_button=wait.until(
            ec.element_to_be_clickable((By.XPATH, "/html/body/div[1]/div[4]/main/section/section/section/section/section[1]/div/div[4]/div[3]/button[3]"))
            )
    except: 
        print("The 'next' button is not clickable. We have navigated through all the pages.")
        break
    else:
        next_button.click() 
        time.sleep(5)
        
driver.quit()

The page is "Yahoo Finance - Stock Market Live, Quotes, Business & Finance News" fully loaded..

The page is "Top Trending Stocks: US stocks with the highest interest today - Yahoo Finance" fully loaded..

The page is "Most Active Stocks: US stocks with the highest trading volume today - Yahoo Finance" fully loaded..

['NU', 'Nu Holdings Ltd.', '', '13.99', '+0.32', '+2.34%', '152.753M', '56.67M', '67.578B', '21.09', '+0.96%', '11.20\n18.98']
['AAL', 'American Airlines Group Inc.', '', '15.67', '-0.64', '-3.92%', '133.164M', '97.279M', '10.364B', '53.33', '+34.02%', '10.09\n18.79']
['SKHYV', 'SK hynix Inc.', '', '168.01', '+168.01', '0.00%', '107.675M', '82.102M', '1.193T', '--', '-8.63%', '151.30\n177.00']
['ONDS', 'Ondas Inc.', '', '7.36', '+0.40', '+5.75%', '103.149M', '71.394M', '4.194B', '15.91', '+203.93%', '1.78\n15.28']
['NVDA', 'NVIDIA Corporation', '', '211.80', '+8.27', '+4.06%', '102.209M', '158.655M', '5.13T', '31.17', '+19.23%', '164.07\n236.54']
['OPEN', 'Opendoor Techno

In [30]:
data

[{'name': 'Nu Holdings Ltd.',
  'symbol': 'NU',
  'price': '13.99',
  'change': '+0.32',
  'volume': '152.753M',
  'market_cap': '67.578B',
  'pe_ratio': '21.09'},
 {'name': 'American Airlines Group Inc.',
  'symbol': 'AAL',
  'price': '15.67',
  'change': '-0.64',
  'volume': '133.164M',
  'market_cap': '10.364B',
  'pe_ratio': '53.33'},
 {'name': 'SK hynix Inc.',
  'symbol': 'SKHYV',
  'price': '168.01',
  'change': '+168.01',
  'volume': '107.675M',
  'market_cap': '1.193T',
  'pe_ratio': '--'},
 {'name': 'Ondas Inc.',
  'symbol': 'ONDS',
  'price': '7.36',
  'change': '+0.40',
  'volume': '103.149M',
  'market_cap': '4.194B',
  'pe_ratio': '15.91'},
 {'name': 'NVIDIA Corporation',
  'symbol': 'NVDA',
  'price': '211.80',
  'change': '+8.27',
  'volume': '102.209M',
  'market_cap': '5.13T',
  'pe_ratio': '31.17'},
 {'name': 'Opendoor Technologies Inc.',
  'symbol': 'OPEN',
  'price': '4.55',
  'change': '+0.07',
  'volume': '98.083M',
  'market_cap': '4.39B',
  'pe_ratio': '--'},
 {

In [31]:
len(data)

332

In [100]:
stocks_df=(
    pd
    .DataFrame(data)
    .apply(lambda col: col.str.strip() if col.dtype == "object" else col)
    
    # extract the other things without numbers and dot
    # .price.str.extract(r"([^0-9.])", expand=False).unique()
    # .price.str.replace(",", "", regex=False)
    # .apply(lambda col: col.str.replace(",", "", regex=False) if col.dtype == "object" else col)
    # .price.str.extract(r"([^0-9.])", expand=False).unique()
    
    
    .assign(
        price=lambda df: df.price.str.replace(",",""),
        change=lambda df: df.change.str.replace("+",""),
        volume= lambda df: df.volume.str.replace("M",""),
        market_cap= lambda df: df.market_cap.apply(lambda val: float(val.replace("B","")) if "B" in val else float(val.replace("T",""))*1000),
        pe_ratio= lambda df: df.pe_ratio.replace("--",np.nan).str.replace(",","")
    )
    # transform columns object to numeric
    .assign(
        price=lambda df: pd.to_numeric(df.price),
        change=lambda df: pd.to_numeric(df.change),
        volume=lambda df: pd.to_numeric(df.volume),
        pe_ratio=lambda df: pd.to_numeric(df.pe_ratio)
    )
    
    # rename the price column
    .rename(
        columns={
            "price":"price_usd",
            "volume":"volume_in_million",
            "market_cap":"market_cap_in_billion"
        }
    )
)

stocks_df

,name,symbol,price_usd,change,volume_in_million,market_cap_in_billion,pe_ratio
0,Nu Holdings Ltd.,NU,13.99,0.32,152.753,67.578,21.09
1,American Airlines Group Inc.,AAL,15.67,-0.64,133.164,10.364,53.33
2,SK hynix Inc.,SKHYV,168.01,168.01,107.675,1193.000,NaN
3,Ondas Inc.,ONDS,7.36,0.40,103.149,4.194,15.91
4,NVIDIA Corporation,NVDA,211.80,8.27,102.209,5130.000,31.17
...,...,...,...,...,...,...,...
327,Baxter International Inc.,BAX,21.80,-0.77,5.047,11.259,NaN
328,British American Tobacco p.l.c.,BTI,58.20,-0.75,5.033,125.637,12.55
329,Sea Limited,SE,109.29,-1.37,5.027,66.938,43.57
330,Almonty Industries Inc.,ALM,15.79,0.77,5.017,4.480,NaN


In [101]:
stocks_df.dtypes

name                      object
symbol                    object
price_usd                float64
change                   float64
volume_in_million        float64
market_cap_in_billion    float64
pe_ratio                 float64
dtype: object

In [67]:
stocks_df.change.str.extract(r"([^0-9.])", expand=False).unique()

array(['+', '-', nan], dtype=object)

There is no need for the `+` sign, so I removed it in the main DataFrame creation code above.

In [77]:
stocks_df.change.str.extract(r"([^0-9.])", expand=False).unique()

array([nan, '-'], dtype=object)

In [80]:
stocks_df.volume.str.extract(r"([^0-9.])", expand=False).unique()

array(['M'], dtype=object)

In [95]:
stocks_df.pe_ratio.str.extract(r"([^0-9.])", expand=False).unique()

array([nan, '-'], dtype=object)

this "-" stands for null values

In [99]:
stocks_df.pe_ratio.str.extract(r"([^0-9.])", expand=False).unique()

array([nan], dtype=object)

In [102]:
stocks_df

,name,symbol,price_usd,change,volume_in_million,market_cap_in_billion,pe_ratio
0,Nu Holdings Ltd.,NU,13.99,0.32,152.753,67.578,21.09
1,American Airlines Group Inc.,AAL,15.67,-0.64,133.164,10.364,53.33
2,SK hynix Inc.,SKHYV,168.01,168.01,107.675,1193.000,NaN
3,Ondas Inc.,ONDS,7.36,0.40,103.149,4.194,15.91
4,NVIDIA Corporation,NVDA,211.80,8.27,102.209,5130.000,31.17
...,...,...,...,...,...,...,...
327,Baxter International Inc.,BAX,21.80,-0.77,5.047,11.259,NaN
328,British American Tobacco p.l.c.,BTI,58.20,-0.75,5.033,125.637,12.55
329,Sea Limited,SE,109.29,-1.37,5.027,66.938,43.57
330,Almonty Industries Inc.,ALM,15.79,0.77,5.017,4.480,NaN


In [107]:
stocks_df.to_excel("yahoo-finance-stocks-data.xlsx",index=False)